### ISSUE TITLE
Erro no ShinyApp

### ISSUE THREAD

**Issue by brunomioto** [AugustoCL/monitor.ipca#1]
O site está desde ontem pelo menos com a mensagem de erro
```
Error in value[[3L]](cond) : valor ausente onde TRUE/FALSE necessário
Calls: local ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execução interrompida
```
Talvez seja pela atualização do IPCA, já que consultei no dia da divulgação e estava tudo certo, mas os dados ainda não estavam atualizados.
Parabéns pelo trabalho! A organização e o dashboard em Shiny são muito bons!

**Comment by AugustoCL** [comment]
Muito obrigado pelo aviso, Bruno. 

O problema foi solucionado e o acesso ao site já está normalizado.
