### ISSUE TITLE
Dataset IGP-M

### ISSUE THREAD

**Issue by brunomioto** [AugustoCL/monitor.ipca#2]
O índice IGP-M pode ser obtido a partir da função `get_series()` do pacote `rbcb`
[Link da função](https://rdrr.io/github/wilsonfreitas/rbcb/man/get_series.html)
Função exemplo: `rbcb::get_series(c('IGP-M'=189), start_date = "2018-01-01", end_date = Sys.Date(), as = "tibble")`

**Comment by AugustoCL** [comment]
Que ótimo. Super prático.

Vou incorporar a série do IGPM na análise, conforme sua sugestão. Assim que tiver pronto, irei te avisar. 

Muito Obrigado.
